### ISSUE TITLE
Virus

### ISSUE THREAD

**Issue by s0kil** [OhGodAnETHlargementPill-r2/AntminerSPD#2]
Scanned the exe file, shows up as virus
https://www.virustotal.com/gui/file/2b02db464be4551a942261fe7c2840993c676b2019f1b0a8c284b8d690be533d

**Comment by CryptoDevloops** [comment]
Hey S0kil, please try again using the latest version of our program.
It looks like you got a false detection there, im not sure why, sorry for any inconvenience made!
